/* asap script loading library
 * MIT License: http://en.wikipedia.org/wiki/MIT_License
 * version:	0.4.2 - 4/15/2010
 * author: andrew dot luetgers at gmail
 */

asap=function(){DOMContentLoaded=null;bindReady=function(){if(!API.readyBound){API.readyBound=true;if(document.readyState==="complete")return ready();if(document.addEventListener){DOMContentLoaded=function(){document.removeEventListener("DOMContentLoaded",DOMContentLoaded,false);API.ready()};document.addEventListener("DOMContentLoaded",DOMContentLoaded,false);window.addEventListener("load",API.ready,false)}else if(document.attachEvent){DOMContentLoaded=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",
DOMContentLoaded);API.ready()}};document.attachEvent("onreadystatechange",DOMContentLoaded);window.attachEvent("onload",API.ready)}var a=false;try{a=window.frameElement===null}catch(b){}if((window.scrollTo||document.documentElement.doScroll)&&a)API.doScrollCheck()}};API={isReady:false,readyBound:false,readyList:[],getVersion:function(){return version},doScrollCheck:function(){if(!API.isReady){try{if(window.scrollTo)window.scrollTo(0,0);else document.documentElement&&document.documentElement.doScroll("left")}catch(a){setTimeout(API.doScrollCheck,
1);return}API.ready()}},ready:function(){if(!API.isReady){if(!document.body)return setTimeout(API.ready,13);API.isReady=true;for(var a;a=API.readyList.shift();)a();this.codeReadyList.length&&this.codeReady()}},domReady:function(a){bindReady();if(a)if(this.isReady){a();this.codeReadyList.length&&this.codeReady()}else this.readyList.push(a);return this},codeReadyList:[],isCodeReady:false,codeReadyQued:false,codeReady:function(a){typeof a=="function"&&this.codeReadyList.push(a);if(this.require.reqQue.length===
0)if(!this.isReady&&!this.codeReadyQued){this.codeReadyQued=true;this.domReady(function(){API.codeReady()})}else{this.readyList.length&&API.domReady();this.isCodeReady=true;if(this.codeReadyList.length)for(;a=this.codeReadyList.shift();)a()}return this}};var g;g=window.XMLHttpRequest&&(window.location.protocol!=="file:"||!window.ActiveXObject)?function(){return new window.XMLHttpRequest}:function(){try{return new window.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}};API.get=function(a){var b=g(),
d=a.url||false,c=a.onSuccess||false,i=a.onError||false;if(!(!b||!d||!c||!i)){b.open("GET",d,true);b.onreadystatechange=function(){if(b.readyState==4)if((window.location.protocol=="file:"||b.status==200)&&b.responseText&&c)c(b.responseText);else i&&i(b.status)};try{b.send("")}catch(s){i&&i(s)}return b}};var f=[],e={},j=/^http:/i,t=/^http:|file:/i,u=/.css$/,v=/[a-z0-9\-\.]+\.[a-z]{2,3}$/i.exec(window.location.host),l="",h=document.getElementsByTagName("head")[0]||document.documentElement,m=0,n=0,o=
0,p={$:function(){"ready"in $&&$.ready()}},w=function(a){var b=j.exec(a),d=window.location.protocol;if(b===null)return true;if(d=="file:")return false;if(b[0]==d)if(a.match(v))return true;return false},k=function(){var a,b;if((a=f[0])&&(b=e[a]))if(b.status=="loaded"){b.status="parsing";x(b.response+" ; (asap.require.evalComplete('"+a+"'));")}else if(b.forceAttatch&&b.status!="loading"){b.status="loading";q(a)}},q=function(a){var b;if(b=e[a]){b.status="loading";y(a,function(){e[a].status="loaded";
asap.require.evalComplete(a)},function(){throw new Error("asap.loadScript ERROR unable to load "+a);})}},y=function(a,b,d){var c=document.createElement("script");c.type="text/javascript";c.charset="utf-8";if(c.readyState)c.onreadystatechange=function(){if(c.readyState=="loaded"||c.readyState=="complete"){c.onreadystatechange=null;b()}};else c.onload=function(){b()};c.onerror=function(){d()};c.src=a;h.appendChild(c)},z=function(){var a=document.createElement("script"),b="script"+(new Date).getTime(),
d=false;a.type="text/javascript";try{a.appendChild(document.createTextNode("window."+b+"=1;"))}catch(c){}h.insertBefore(a,h.firstChild);if(window[b]){delete window[b];d=true}h.removeChild(a);return d}(),x=function(a){var b=document.createElement("script");b.type="text/javascript";if(z)b.appendChild(document.createTextNode(a));else b.text=a;h.insertBefore(b,h.firstChild);h.removeChild(b)},A=function(a){var b=document.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a;h.appendChild(b)},
r=function(a,b){if(a.match(u))A(a);else{theFile=t.exec(a)?a:l+a;if(!e[theFile]){API.isCodeReady=false;e[theFile]={status:"qued",xhr:false,response:false,forceAttatch:b||false};f.push(theFile);m++}}},B=function(a){var b=e[a];if(!w(a)||b.forceAttatch){o++;b.forceAttatch=true;k(a)}else{o++;b.xhr=asap.get({url:a,onSuccess:function(d){var c=e[a];if(d)c.status="loaded";c.response=d;c.xhr=false;f[0]==a&&k()},onError:function(d){var c=e[a];if(typeof d=="object"&&"message"in d){c.status="ERROR";throw new Error("asap.get ERROR: "+
d.message+" on "+a);}else if(d!==404)q(a);else{c.status="ERROR";throw new Error("asap.get ERROR: loading external resource: status code: "+d+" on "+a);}}})}};API.domReady(k);API.require=function(a,b){var d,c;l=a.root||"";b=b||a.debug||window.location.href.match("asap=debug");if(typeof a=="object"){a=a.files||a;c=a.length||0;for(d=0;d<c;d++)r(a[d],b)}else r(a,b);for(file in e)e.hasOwnProperty(file)&&B(file);return this};API.require.evalComplete=function(a){var b;if(f[0]==a&&(b=e[a])&&(b.status=="parsing"||
b.status=="loaded")){n++;f.splice(0,1);delete e[a];if(f.length)k();else n==m&&API.codeReady();for(api in p)window[api]&&p[api]()}};API.require.reqQue=f;return API}();(function(g,f,e,j){if(g[f]==null&&g[e]){g[f]="loading";g[e](j,e=function(){g[f]="complete";g.removeEventListener(j,e,false)},false)}})(document,"readyState","addEventListener","DOMContentLoaded");
